### ISSUE TITLE
Unknown file extension ".ts" for .../IMPORTED_FILE.ts

### ISSUE THREAD

**Issue by n1kk** [aduth/esbuild-esm-loader#1]
Trying to import ts file in local project and getting this error:

```
Unknown file extension ".ts" for /PROJECT_PATH/svelte-config.ts
```

This is the command I run: 

```bash 
node --loader esbuild-esm-loader ./node_modules/@sveltejs/kit/svelte-kit.js dev 
```

Tried `--experimental-loader=` version too, the same result.

SvelteKit loads `svelte.config.js` where I have just: 

```js
import config from "./svelte-config";

export default config;
```

`svelte-config.ts` file contains exported config

Is there anything else needed to be done to make `.ts` a recognized extension?

**Comment by aduth** [comment]
Hi 👋 

Node.js v16.12 changed the way that loaders work, which the latest version of this library now targets. I think I’ve seen this error when running an older version. Can you check to make sure you’re running >=16.12? Alternatively, if you can’t do that, v0.1 of this library targets the older format.

**Comment by n1kk** [comment]
Thanks for your reply, that did the trick! Got v16.13 and it loaded `svelte-config.ts` file, but then it tries to load other local `.ts` files and it can't find them for some reason. 

```
Cannot find module '/PROJECT_PATH/mdsvex.config' imported from /PROJECT_PATH/svelte-config.ts
```
 I import files without extension, like `import config from "./svelte-config";` `import mdsvexConfig from "./mdsvex.config";` and those files are included in my `ts-config`. I don't think es-build uses it though, it just strips types out, right?

If I place everything in the `svelte-config.ts` it starts the dev server and everything seems to run.

**Comment by n1kk** [comment]
Hm, so adding `.ts` files to all the other imports within a `svelte-config.ts` files works, but the `svelte-config` itself must be imported without the `.ts` extension.

This is a bit confusing,  and now IDE is complaining about `.ts` extensions in the imports.

Is there a way to make it import all the other files without `.ts` extension too?

**Comment by aduth** [comment]
By default, Node ESM imports do [require the file extension](https://nodejs.org/docs/latest-v16.x/api/esm.html#mandatory-file-extensions), and I'd guess it's a lint rule like [`eslint-plugin-import/extensions`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md) that's causing your IDE to complain, or maybe it just doesn't like the `.ts` extension. That being said, in a recent version I published, I had meant to support emulation for these extensionless paths, so it was surprising to me that it's not working. Looking closer, I think it has to do with the fact that you're using a root-relative import path `'/PROJECT_PATH/mdsvex.config'`, which I hadn't accounted for.

I just published a new version 0.2.2 which should make this work a little better. Can you update and give it a try?

**Comment by n1kk** [comment]
I don't use the root-relative import path, the actual import is `import mdsvexConfig from "./mdsvex.config";` the files are next to each other. The root path is appearing from the error in the console.

Here is the structure
```
├── config
|  ├── svelte-config.ts
|  ├── mdsvex.config.ts
└── svelte.config.js
```
Tried the latest version, seems to be the same behavior:
- with `.ts` it works but the IDE is showing an error, and it is a typescript error `TS2691: An import path cannot end with a '.ts' extension. Consider importing './mdsvex.config.js' instead.`, I guess since es-build is not actually compiling it's not a problem.
- with ".js" it shows this error: `ENOENT: no such file or directory, open '/home/n1kk/dev/www/gogetgame.com/config/mdsvex.config.js'`
- and with no extension it shows this error `Cannot find module '/home/n1kk/dev/www/gogetgame.com/config/mdsvex.config' imported from /home/n1kk/dev/www/gogetgame.com/config/svelte-config.ts`

With ".js" extension it actually resolves by typescript to the correct `.ts` file, seems that they've added it to be able to create esm compatible output, sad that they can't add the extension by the compiler automatically.

So it's still the same, the first import from the entry file (svelte.config.js) -> `import config from "./config/svelte-config";` resolves fine, but imports inside of it don't.

**Comment by aduth** [comment]
Ok, I think I spotted the issue: Extensionless imports where the file name includes multiple dots (e.g. `mdsvex.config.ts`) were not being resolved correctly. I think I've fixed this in the latest release, v0.2.3. Could you update once more to see if it helps?

**Comment by n1kk** [comment]
It works now. Thanks!

If I remove all extensions, everything works when I run it with esbuild, but if I just compile ts and run it with the regular node it fails since it expects `.js` extensions now when referencing files directly. Not an issue for me, since I can compile configs but don't plan to run it via pure node. Do you plan to support the new esm way too?

I'll resolve this since my problem is solved, thanks again for your work!

**Comment by aduth** [comment]
I might not be totally following what you're needing, but it sounds like you want the extensionless resolution behavior of this loader, but leave out the ESBuild transformation? It's not something I'd really planned to support, since the loader is meant primarily for the ESBuild transformation itself. Technically you could still use the loader even for your compiled assets, though that would be rather wasteful, since it's already compiled at that point.

Maybe you could grab everything up-to-but-excluding the `load` function in [`index.js`](https://github.com/aduth/esbuild-esm-loader/blob/main/index.js), and have that be your runtime loader for extensionless resolution?

Alternatively, I'm curious about whether there's an option to let the extension be included. I see some relevant discussion for TypeScript in https://github.com/microsoft/TypeScript/issues/37582 and https://github.com/microsoft/TypeScript/issues/16577. Maybe adding `.js` as the file extension (even for `.ts` files) is the solution? This is also what the error message you originally mentioned was indicating.

---

**Edit:** This also seems to be what TypeScript documentation recommends:

>This also means paths resolve differently between `.ts` files that are ES modules and ones that are CJS modules. For example, let’s say you have the following code today:
>
>```ts
>// ./foo.ts
>export function helper() {
>    // ...
>}
>// ./bar.ts
>import { helper } from "./foo"; // only works in CJS
>helper();
>```
>
>This code works in CommonJS modules, but will fail in ES modules because relative import paths need to use extensions. As a result, it will have to be rewritten to use the extension of the output of `foo.ts` - so `bar.ts` will instead have to import from `./foo.js`.
>
>```ts
>// ./bar.ts
>import { helper } from "./foo.js"; // works in ESM & CJS
>helper();
>```
>
>This might feel a bit cumbersome at first, but TypeScript tooling like auto-imports and path completion will typically just do this for you.

https://www.typescriptlang.org/docs/handbook/esm-node.html
